name: Laravel CI/CD

on:
  push:
    branches:
       ["main"]
  pull_request:
    branches:
     ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Repozitoriyadan kodni yuklash
      uses: actions/checkout@v3

    - name: PHP 8.1 ni o'rnatish
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, exif, bcmath, intl, pdo_mysql
        coverage: none

    - name: Composer o'rnatish
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Env faylni yaratish
      run: cp .env.example .env

    - name: Laravel kalitni yaratish
      run: php artisan key:generate

    - name: Ma'lumotlar bazasi migratsiyalari
      run: php artisan migrate --force

    
